
server:
  port: 8080

spring:
  application:
    name: calipso

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/calpso_sms_db}
    username: ${SPRING_DATASOURCE_USERNAME:calipso_user}
    password: ${SPRING_DATASOURCE_PASSWORD:calipso_password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
